### ISSUE TITLE
Zif.roll modifer default should be zero

### ISSUE THREAD

**Issue by davebytemfg** [danhealy/dragonruby-zif#28]
```
->  Zif.roll(dice: 1, sides: 1)
=> 3
```

That was unexpected until I looked up the def and then it made sense.

from zif.rb
```
  def self.roll(dice: 4, sides: 16, modifier: 2)
```

Might be better to default the modifier to zero.

Yes, I could also use the roll_raw call instead, but invoking the rule of least surprise.

**Comment by danhealy** [comment]
`roll_v2` now has a default `modifier` of `0`

`roll` will be changed with this default in the next breaking release
